site_name: Design Technology - Research Log
docs_dir: docs
repo_url: https://github.com/asg-architects/Design-Technology
repo_name: asg-architects/design-technology
edit_uri: edit/main/docs/
markdown_extensions:
  - tables
plugins:
  - search
  - table-reader
  - git-revision-date-localized:
      enable_creation_date: true
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil 
    view: material/eye
  features:
#    - navigation.tabs
#    - navigation.sections
#    - toc.integrate
#    - navigation.top
    - search.suggest
    - search.highlight
#    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
